name: GradAttack CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Install SafeGrad
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
